name: update_db_from_boinc_test
run-name: update_db_from_boinc1
on:
  schedule:
    - cron: '*/3 * * * *'
 
jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        env: # Or as an environment variable
          user_pass: ${{ secrets.DB_USER }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python db/scripts/update_db_from_boinc.py $user_pass

